const maquiagem = [
  {
    tipo: 'Olhos',
    link: 'olhos',
    img: 'https://i.ibb.co/Mp2CNg1/image-134.png',
    hover: 'Realce seus olhos com nossos produtos de maquiagem, destacando sua expressão de maneira autêntica e moderna.',
    texto_card:'Olhos',
    produtos: [
      {
          id: 1,
          nome:'Contorno Labial Roseletis',
          descricao:'Quem Disse, Berenice? 1,1g',
          preco:29.90,
          img: 'https://res.cloudinary.com/beleza-na-web/image/upload/w_1500,f_auto,fl_progressive,q_auto:eco,w_800/v1/imagens/products/B77898/QDB_Lapis_Contorno_Lab_Roseletis_B77898.jpg',
          quantidade: 1,
        },
        {
          id: 2,
          nome:'Máscara de Cílios Scandallashes',
          descricao:'Make B. 10g',
          preco:72.90,
          img: 'https://res.cloudinary.com/beleza-na-web/image/upload/w_1500,f_auto,fl_progressive,q_auto:eco,w_800/v1/imagens/products/B77220/B77220-Mascara-Cilios-Scandallashes-Make-B_aberta.jpg',
          quantidade: 1,
        },
        {
          id: 3,
          nome:'Delineador Líquido',
          descricao:'Para Olhos Preto Make B.',
          preco:51.90,
          img: 'https://res.cloudinary.com/beleza-na-web/image/upload/w_1500,f_auto,fl_progressive,q_auto:eco,w_800/v1/imagens/products/B53427/53427_MAKE-B_DELINEADOR-RESISTENTE-PRETO_FRONTAL_1.jpg',
        },
        {
          id: 4,
          nome:'Make B. Sombra Líquida',
          descricao:'Femme Extreme 5,6 ml - Marsala',
          preco:40.70,
          img: 'https://res.cloudinary.com/beleza-na-web/image/upload/w_1500,f_auto,fl_progressive,q_auto:eco,w_800/v1/imagens/products/B82928/82928-01.png',
          quantidade: 1,
        },
        {
          id: 5,
          nome:'Sombra Mate Compacta ',
          descricao:'by Manu Gavassi',
          preco:26.30,
          img: 'https://res.cloudinary.com/beleza-na-web/image/upload/w_1500,f_auto,fl_progressive,q_auto:eco,w_800/v1/imagens/products/B83599/Slide20.JPG',
          quantidade: 1,
        },
    ]
  },
  {
    tipo: 'Blush',
    link: 'blush',
    img: 'https://i.ibb.co/TcF51wY/image-119-1.png',
    hover: 'Com um toque suave de blush, as bochechas ganham um rubor sutil, irradiando um frescor que parece capturar a luminosidade do dia.',
    texto_card:'Blush',
    produtos: [
      {
          id: 1,
          nome:'Blush Ameixa em Bastão',
          descricao:'intense by Manu Gavassi 5,5g',
          preco:28.10,
          img: 'https://i.ibb.co/5MjZ2T5/p-1-blush.png',
          quantidade: 1,
        },
        {
          id: 2,
          nome:'Blush em Pó',
          descricao:'Blush em Pó',
          preco:59.90,
          img: 'https://i.ibb.co/KwCNWmW/p-2-blush.png',
          quantidade: 1,
        },
        {
          id: 3,
          nome:'Pó Compacto Facial Multiefeitos',
          descricao:'Napolitano Quem Disse, Berenice? 18g',
          preco:89.90,
          img: 'https://i.ibb.co/2qR9xsN/p-3-boca.png',
          quantidade: 1,
        },
        {
          id: 4,
          nome:'Paleta Blush',
          descricao:'Cherry Make B. Hit, 8g',
          preco:83.90,
          img: 'https://i.ibb.co/tsFX1P3/p-4-dr-blush.png',
          quantidade: 1,
        },
        {
          id: 5,
          nome:'Blush Compacto Rosadinha',
          descricao:'Quem Disse, Berenice? 2g',
          preco:55.90,
          img: 'https://i.ibb.co/km1813k/p-5-blush.png',
          quantidade: 1,
        },
        
    ]
  },

  {
    tipo: 'Boca',
    link: 'boca',
    img: 'https://i.ibb.co/bB4W2Yy/image-119.png',
    hover: 'Um batom cuidadosamente selecionado não apenas colore os lábios, mas também revela sua confiança e estilo de forma sutil e autêntica.',
    texto_card:'Boca',
    produtos: [
      {
          id: 1,
          nome:'Batom Mate',
          descricao:'Brown Stone Make B. 3,6 g',
          preco:56.90,
          img: 'https://res.cloudinary.com/beleza-na-web/image/upload/w_1500,f_auto,fl_progressive,q_auto:eco,w_800/v1/imagens/product/B53036/ed3fe97a-2580-4554-8d21-a01806a8824a-bot-53036-make-b-mini-batom-amostra.jpg',
          quantidade: 1,
        },
        {
          id: 2,
          nome:'Lápis Batom ',
          descricao:'Instalip Vinho Intense 1,2g',
          preco:24.90,
          img: 'https://res.cloudinary.com/beleza-na-web/image/upload/w_1500,f_auto,fl_progressive,q_auto:eco,w_800/v1/imagens/products/B76601/Slide6.JPG',
          quantidade: 1,
        },
        {
          id: 3,
          nome:'Batom Marsala',
          descricao:'Intense Stick Glossy 3,2g',
          preco:31.90,
          img: 'https://res.cloudinary.com/beleza-na-web/image/upload/w_1500,f_auto,fl_progressive,q_auto:eco,w_800/v1/imagens/product/B50381/92452801-6d03-45fe-94d3-361b60c51bca-bot-50381-intense-batom-gloss-stick-rosa-sensorial-02.jpg',
          quantidade: 1,
        },
        {
          id: 4,
          nome:'Gloss Labial Rosa',
          descricao:'Tutti Frutti Intense Bubbaloo 5ml',
          preco:39.90,
          img: 'https://res.cloudinary.com/beleza-na-web/image/upload/w_1500,f_auto,fl_progressive,q_auto:eco,w_800/v1/imagens/products/B01080/INTENSE-GLOS-LAB-BUBBALOO-5ml_B01080_.jpg',
          quantidade: 1,
        },
        {
          id: 5,
          nome:'Gloss Labial',
          descricao:'Sweet Nude Make B. 5 ml',
          preco:57.90,
          img: 'https://res.cloudinary.com/beleza-na-web/image/upload/w_1500,f_auto,fl_progressive,q_auto:eco,w_800/v1/imagens/product/B80817/d5d405ba-738d-4e9a-a6ab-d018c5ee346f-gloss-labial-sweet-nude-make-b-5-ml.png',
          quantidade: 1,
        },
    ]
  },
  {
    tipo: 'Rosto',
    link: 'rosto',
    img: 'https://i.ibb.co/VSzg4k3/image-135.png',
    hover: 'A maquiagem para o rosto realça a beleza única de cada pessoa, sem exageros, apenas realçando o que já é incrível.',
    texto_card:'Rosto',
    produtos: [
      {
          id: 1,
          nome:'Refil Base Líquida',
          descricao:'Cushion Cor 60 Make B. 14g',
          preco:71.90,
          img: 'https://i.ibb.co/gV247QQ/p-1-base.png',
          quantidade: 1,
        },
        {
          id: 2,
          nome:'Base Líquida Make B.',
          descricao:'Glycolic TX Cor 210 30g',
          preco:79.90,
          img: 'https://i.ibb.co/sQ6dcjR/p-2-rosto.png',
          quantidade: 1,
        },
        {
          id: 3,
          nome:'Base em Pó Mineral',
          descricao:'Cor 20 Make B. 5,5g',
          preco:83.90,
          img: 'https://i.ibb.co/grhH7V0/p-3-rosto.png',
          quantidade: 1,
        },
        {
          id: 4,
          nome:'Pó Compacto',
          descricao:'Facial Cor 30 Intense 5g',
          preco:59.90,
          img: 'https://i.ibb.co/d5hbmmz/p-4-rosto.png',
          quantidade: 1,
        },
        {
          id: 5,
          nome:'Pó Compacto',
          descricao:'Facial Cor 70 Intense 5g',
          preco:59.90,
          img: 'https://i.ibb.co/88JDT4z/p-5-rosto.png',
          quantidade: 1,
        },
        
    ]
  },
  {
    tipo: 'Brilho',
    link: 'brilho',
    img: 'https://i.ibb.co/syy2fFy/image-136.png',
    hover: 'Descubra a luminosidade sofisticada que sua maquiagem pode ter, proporcionando um brilho que reflete sua beleza autêntica.',
    texto_card:'Brilho',
    produtos: [
      {
          id: 1,
          nome:'Pó Iluminador Perfumado',
          descricao:'Rosto e Corpo Make B. Rosé 12g',
          preco:95.90,
          img: 'https://i.ibb.co/267yqKx/p-1-brilho.png',
          quantidade: 1,
        },
        {
          id: 2,
          nome:'Pó Compacto Facial',
          descricao:'Iluminador Gold Make B. 5,4g',
          preco:76.90,
          img: 'https://i.ibb.co/5F3j6Ft/p-2-brilho.png',
          quantidade: 1,
        },
        {
          id: 3,
          nome:'Iluminador Facial',
          descricao:'Perolado em Bastão Intense 5,5g',
          preco:45.90,
          img: 'https://i.ibb.co/XSb3g60/p-3-brilho.png',
          quantidade: 1,
        },
        {
          id: 4,
          nome:'Glitter Líquido Multiuso ',
          descricao:'Brancotix Quem Disse, Berenice? 4ml',
          preco:49.90,
          img: 'https://i.ibb.co/n0DVJYX/p-4-brilho.png',
          quantidade: 1,
        },
        {
          id: 5,
          nome:'Batom Líquido Diamond',
          descricao:'Dourado Luxury Make B. 5ml',
          preco:59.90,
          img: 'https://i.ibb.co/Vjp1TqN/p-5-brilho-1.png',
          quantidade: 1,
        },
    ]
  }
]

export { maquiagem }
